### ISSUE TITLE
Make the code base PEP8!

### ISSUE THREAD

**Issue by bderstine** [bderstine/WebsiteMixer-App-Base#4]
I should have done this sooner, but I knew I was going to redo most of the code base. But before a final 2.0 version go live, I'd like to see the code be PEP8 compliant. Some of the forks look like they had to do this too sooooo....

**Comment by chuckclift** [comment]
I would be interested in doing this.

**Comment by chuckclift** [comment]
When I run pep8, I am getting a lot of errors with the models.py file.  With a lot of the calls to db.Table end up being pretty messy when changed to PEP8:

This:

user_roles = db.Table('user_roles',
    db.Column('id', db.Integer, primary_key=True, autoincrement=True),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id', ondelete='cascade')),
    db.Column('role_id', db.Integer, db.ForeignKey('role.id', ondelete='cascade'))
)

becomes this:

user_roles = db.Table('user_roles',
                                   db.Column('id', db.Integer, primary_key=True, 
                                                      autoincrement=True),
                                   db.Column('user_id', db.Integer, 
                                                      db.ForeignKey('user.id', ondelete='cascade')),
                                   db.Column('role_id', db.Integer, db.ForeignKey('role.id', 
                                                      ondelete='cascade'))
)

I think that it could be broken up into something like this:

roles_id =  db.Column('id', db.Integer, primary_key=True, autoincrement=True)
roles_user_id = db.Column('user_id', db.Integer, 
                                             db.ForeignKey('user.id', ondelete='cascade'))
roles_role_id = db.Column('role_id', db.Integer, 
                                            db.ForeignKey('role.id', ondelete='cascade'))

user_roles = db.Table('user_roles', roles_id, roles_user_id, roles_role_id)

What are your thoughts?

**Comment by bderstine** [comment]
Honestly, roles haven't been fully implemented yet, so I'm ok with updating them so it works with PEP8. Was that the only table model that needed to be updated? if it is, we can just remove it for now until it's needed, but I suspect other tables may need the same magic.

**Comment by chuckclift** [comment]
There were seven of them at the top of the models.py file that were throwing that pep8 error. Most of the other things in the repo are easy to translate into pep8.

**Comment by chuckclift** [comment]
I just made a commit that makes the models.py pep8 compliant.  
https://github.com/chuckclift/WebsiteMixer-App-Base/blob/master/websitemixer/models.py

Does that look good?

**Comment by bderstine** [comment]
It does, and it's pep8. I kinda went a different way with my indentations. I dislike the large indents of white space, so I tried the other method to get it to pass... What do you think of mine? I just committed it too. Since both are technically pep8 compliant, which would you rather like to see if you were going to update code you found online?

**Comment by chuckclift** [comment]
I like the way that yours looks.  I'm going to pull in that change and go on to the rest of the files.

**Comment by bderstine** [comment]
ok thanks!!! let me know if you run into any other weirdness

**Comment by chuckclift** [comment]
I finished up the pep8 work, I'm going to do a test installation to make sure that everything works

**Comment by bderstine** [comment]
I had tried your code base, and I think my mess of imports breaks when the code is in the PEP8/cleaned up format. I need to redo the imports. But if you want to commit your changes to the develop branch (I created it over the weekend), I can include your changes with my other clean up efforts?? let me know

**Comment by chuckclift** [comment]
I found what was causing the error.  In the new **init**.py file, the line: 

from functions import *

near the top of the file, while in the previous version, it is near the end of the file in the old code.

   I found a way to get around the issue that involves creating a separate python file for importing sqlalchemy [1].  The **init**.py file then imports db from the file (shared.py), and uses db.init_app(app) in place of "db = SQLAlchemy(app)". Now, instead of importing db from websitemixer, they import it from websitemixer.shared.  
    I did a basic installation, and it seems to work.  I did the installation and added a few posts.  I ran the pep8 check, and everything is good on that front.  

[1] http://stackoverflow.com/questions/26691616/flask-sqlalchemy-import-models-going-wrong

**Comment by chuckclift** [comment]
Do you think that the addition of another file (shared.py) is worth it?

**Comment by bderstine** [comment]
I think it's great! Thank you for looking into this!

Reading the updating documentation for 0.11 flask and sqlalchemy, it mentions importing an external module for it too, it calls it database.py though - http://flask.pocoo.org/docs/0.11/patterns/sqlalchemy/

At first I was ok with a shared.py, but the more I think about it, I think it would be easier if the file was just database.py so the importing of modules later makes more sense and we aren't supporting a gnarly, multi-purpose shared.py. Can you rename it, update your import, and do a pull request? I'd love to get your code included in the repo!

**Comment by bderstine** [comment]
Actually, I think I can do the pull request too. I might do that and then change the file name after it's merged.

**Comment by bderstine** [comment]
Actually, I merged your changes into the main repo! I can rename the file myself and get some release notes ready for the next release soon! Thank you!!! This is a HUGE leap forward for the code base!

**Comment by bderstine** [comment]
I'm going to close this issue since you solved the issue of the PEP8 and the circular import issue. This is the first actual pull request for this project so thank you!!!

**Comment by chuckclift** [comment]
Great!
